"""
HTML email template builder for flight result emails (ABA-8).

build_email_html() wraps the agent-generated body content in a fully
structured HTML email with inline CSS for broad email client compatibility.
"""


def build_email_html(subject: str, body_html: str) -> str:
    """
    Wrap body_html in a complete HTML email template.

    Args:
        subject:   Email subject line (used in the header banner).
        body_html: HTML content block generated by the agent — typically
                   a flight results table and route summary.

    Returns:
        A complete HTML string ready to pass to gmail_send_email body param.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{subject}</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f6f8;font-family:Arial,Helvetica,sans-serif;">

  <!-- Wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f6f8;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

          <!-- Header -->
          <tr>
            <td style="background-color:#1a1a2e;padding:24px 32px;">
              <p style="margin:0;font-size:20px;font-weight:bold;color:#ffffff;letter-spacing:0.5px;">
                ✈ Kāishǐ - Your Airline Booking Assistant
              </p>
              <p style="margin:6px 0 0;font-size:13px;color:#a0aec0;">
                Your flight options, delivered
              </p>
            </td>
          </tr>

          <!-- Greeting -->
          <tr>
            <td style="padding:28px 32px 8px;">
              <p style="margin:0;font-size:16px;color:#2d3748;">
                Hi there,
              </p>
              <p style="margin:8px 0 0;font-size:15px;color:#4a5568;line-height:1.6;">
                Here are your flight options as requested. Review the details below and book directly with the airline.
              </p>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:16px 32px;">
              <hr style="border:none;border-top:1px solid #e2e8f0;margin:0;">
            </td>
          </tr>

          <!-- Flight content (agent-generated) -->
          <tr>
            <td style="padding:0 32px 24px;">
              <div style="font-size:14px;color:#2d3748;line-height:1.7;">
                {body_html}
              </div>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 32px;">
              <hr style="border:none;border-top:1px solid #e2e8f0;margin:0;">
            </td>
          </tr>

          <!-- Disclaimer footer -->
          <tr>
            <td style="padding:20px 32px 28px;">
              <p style="margin:0;font-size:12px;color:#a0aec0;line-height:1.6;">
                <strong>Disclaimer:</strong> This is a proof-of-concept application.
                Flight prices, availability, and schedules shown are <strong>not real</strong>
                and are for demonstration purposes only. Do not use this information for
                actual travel bookings.
              </p>
              <p style="margin:10px 0 0;font-size:12px;color:#cbd5e0;">
                Sent by Airline Booking Assistant POC &mdash; powered by Claude AI
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>"""
